# Generated by Django 4.1 on 2026-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0033_procedure_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsession",
            name="require_all_visible",
            field=models.BooleanField(
                default=False,
                help_text="Snapshot of the RequireAllVisible preference at session start. When True the flow gate covers every visible item (optional included) and no item is auto-skipped — each visible row must be checked.",
            ),
        ),
    ]
