# Generated by Django 4.1 on 2026-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0034_flightsession_require_all_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsession",
            name="last_datarefs",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Latest dataref snapshot POSTed by the plugin. Stored here rather than in process memory because the app runs under Passenger with several worker processes — a plugin POST only reaches one worker, so a process-local cache makes every other worker evaluate rules against a stale snapshot.",
                null=True,
            ),
        ),
    ]
