# Generated by Django 5.2.1 on 2026-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0035_flightsession_last_datarefs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="api_key_hash",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="api_key_sha256",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
