# Generated by Django 5.2.1 on 2026-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0036_api_key_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsession",
            name="plugin_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
