# Generated by Django 5.2.1 on 2026-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0037_flightsession_plugin_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_cleanup",
                    models.DateTimeField(
                        help_text="When run_cleanup last started. Advanced by claim(), not by the cleanup finishing — a crashed run must not hold the lock."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "maintenance state",
            },
        ),
    ]
