"""
Django settings for smart_training_checklist project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from .. import __version__

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
VERSION = __version__

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "checklist.apps.ChecklistConfig",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smart_training_checklist.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "checklist.context_processors.sop_context",
            ],
        },
    },
]

WSGI_APPLICATION = "smart_training_checklist.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MOCK_TOKEN = config("X-Auth-Token", default=None)

# Polling interval for the JS checklist polling loop (milliseconds).
# Override in dev.py / prod.py if needed.
#
# Half of the old 1500 ms. The wait for the next poll is the largest single
# term in the delay between a pilot moving a switch and the row ticking on
# screen — roughly half the total, against ~250 ms for the plugin's own tick
# and a few ms of server work — so halving it takes ~375 ms off the average.
#
# It costs reads only: poll_view's single write is guarded by
# `if new_state != prev_state` (api_views.py), and its query count is flat in
# procedure size and ceiling-tested (test_query_counts.py).
POLL_INTERVAL_MS = 750

# ── Plugin compatibility window ────────────────────────────────────────────── #
#
# PLUGIN_MIN_VERSION  — plugins below this tuple are blocked (response includes
#                       plugin_status: "blocked" and the update URL).
# PLUGIN_WARN_BELOW   — plugins at or above MIN but below this get a warning.
#
# Sliding-window policy: when a new minor version ships, the previous minor
# version moves to "warn" and the one before that moves to "blocked".
# Patch-only releases (1.0.x → 1.0.y) never change the window.

# Set at the 1.1.0 release. Nothing in 1.1.0 changed the wire protocol — the
# changes are a dataref-type cache, a persistent worker thread and a faster
# tick — so a 1.0.2 plugin still works correctly, just slower. Blocking it
# would be gratuitous; warning is what the window is for.
#
# Setting MIN to the current version instead would leave the warn band empty,
# because "blocked" is tested first and would catch everything below it — so
# nobody would ever see a warning.
PLUGIN_MIN_VERSION = (1, 0, 2)   # the oldest version ever released; blocks nothing that exists
PLUGIN_WARN_BELOW  = (1, 1, 0)   # anything older than the current release is nudged

# Stable permalink to the latest plugin zip attached to the GitHub release.
# The GitHub Actions workflow must upload the asset under this exact filename.
PLUGIN_DOWNLOAD_URL = (
    "https://github.com/chezhj/simflow"
    "/releases/latest/download/xflow-plugin.zip"
)

# Auth redirects
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "checklist:start"
LOGOUT_REDIRECT_URL = "checklist:start"
