"""
Plugin version window, and how it reaches the pilot.

The plugin learns its own status from an API response and writes it to
X-Plane's Log.txt. Nobody reads that, so the browser banner is the only place
an outdated plugin is actually visible — these cover the path from the
X-Plugin-Version header to the poll response that drives it.
"""

# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring

import json

from django.contrib.auth import get_user_model
from unittest.mock import patch

from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from checklist.models import FlightSession, Procedure
from checklist.plugin_views import plugin_status_for_version
from checklist.tests.testFactories import CheckItemFactory, SOPFactory

User = get_user_model()


@patch("checklist.plugin_views.CURRENT_PLUGIN_VERSION", "2.3.4")
class TestVersionWindow(TestCase):
    """
    The window is derived, not configured: major behind is blocked, minor
    behind is warned, patch behind is fine, newer is fine. Pinned against a
    fixed CURRENT_PLUGIN_VERSION so these do not need editing at every plugin
    release — which is the entire point of the change.
    """

    def test_the_same_version_is_ok(self):
        self.assertEqual(plugin_status_for_version("2.3.4"), "ok")

    def test_a_patch_behind_is_ok(self):
        """Patch releases never move the window."""
        self.assertEqual(plugin_status_for_version("2.3.0"), "ok")
        self.assertEqual(plugin_status_for_version("2.3.3"), "ok")

    def test_a_minor_behind_is_warned_not_blocked(self):
        """
        Still works — it is missing fixes, not speaking a different protocol.
        Blocking would strand a pilot mid-flight over a performance change.
        """
        self.assertEqual(plugin_status_for_version("2.2.9"), "warn")
        self.assertEqual(plugin_status_for_version("2.0.0"), "warn")

    def test_a_major_behind_is_blocked(self):
        """A major bump is what the project uses to mean the wire changed."""
        self.assertEqual(plugin_status_for_version("1.9.9"), "blocked")
        self.assertEqual(plugin_status_for_version("0.7.0"), "blocked")

    def test_a_newer_plugin_is_ok_not_blocked(self):
        """
        A plugin release is tagged BEFORE the app release that accompanies it,
        so there is always a window where a keen pilot runs a plugin this app
        has not heard of. Blocking them would punish them for the project's
        own release order — and the app, not the plugin, is the one behind.
        """
        for newer in ("2.3.5", "2.4.0", "3.0.0"):
            with self.subTest(newer=newer):
                self.assertEqual(plugin_status_for_version(newer), "ok")

    def test_a_two_part_version_is_compared_not_rejected(self):
        self.assertEqual(plugin_status_for_version("2.3"), "ok")
        self.assertEqual(plugin_status_for_version("1.9"), "blocked")

    def test_an_unreadable_version_warns_rather_than_blocking(self):
        """
        Blocking withholds session data and stops the checklist following the
        sim — too much to do to a client that merely failed to identify
        itself. It still does not pass as current.
        """
        for raw in ("", "   ", "not-a-version", None):
            with self.subTest(raw=raw):
                self.assertEqual(plugin_status_for_version(raw or ""), "warn")


class TestAnUnreadableMarkerBlocksNobody(TestCase):

    @patch("checklist.plugin_views.CURRENT_PLUGIN_VERSION", "not-a-version")
    def test_every_version_is_ok_when_our_own_marker_is_broken(self):
        """
        Failing closed here would lock every pilot out of their checklist over
        a fact this app lost track of. It logs instead.
        """
        with self.assertLogs("checklist.plugin_views", level="ERROR"):
            self.assertEqual(plugin_status_for_version("0.1.0"), "ok")


class TestTheMarkerMatchesTheShippedPlugin(TestCase):
    """
    checklist/plugin_version.py is generated by scripts/bump_plugin.py in the
    same commit that bumps PI_xFlow.py. Nothing at runtime can notice if the
    two drift, because release-deploy.yaml excludes xplane_plugin from the
    rsync — the server never sees PI_xFlow.py and has only the marker to go
    on. A test run from the repo is the only place both files exist together.

    If this fails, the app is classifying pilots' plugins against the wrong
    idea of "current": too low and nobody is ever warned, too high and
    everyone running the actual current release is nagged or blocked.
    """

    def test_the_marker_matches_the_plugin_source(self):
        import re
        from pathlib import Path

        from django.conf import settings

        from checklist.plugin_version import CURRENT_PLUGIN_VERSION

        plugin = Path(settings.BASE_DIR) / "xplane_plugin" / "xFlow" / "PI_xFlow.py"
        match = re.search(
            r'^PLUGIN_VERSION\s*=\s*["\']([^"\']+)["\']',
            plugin.read_text(encoding="utf-8"),
            re.MULTILINE,
        )
        self.assertIsNotNone(match, "PLUGIN_VERSION not found in the plugin")
        self.assertEqual(
            CURRENT_PLUGIN_VERSION,
            match.group(1),
            "checklist/plugin_version.py has drifted from PI_xFlow.py — "
            "scripts/bump_plugin.py updates both, so this means one was "
            "edited by hand",
        )

    def test_the_shipped_plugin_classifies_as_current(self):
        """A release must never ship an app that nags about its own plugin."""
        from checklist.plugin_version import CURRENT_PLUGIN_VERSION

        self.assertEqual(plugin_status_for_version(CURRENT_PLUGIN_VERSION), "ok")


@patch("checklist.plugin_views.CURRENT_PLUGIN_VERSION", "1.1.0")
class TestVersionReachesTheBrowser(TestCase):

    def setUp(self):
        self.user = User.objects.create_user(username="pilot", password="pw")
        self.profile = self.user.profile
        self.raw_key = self.profile.set_api_key()

        sop = SOPFactory()
        self.procedure = Procedure.objects.create(
            title="Before Start", step=1, slug="before-start", sop=sop
        )
        CheckItemFactory(procedure=self.procedure, step=1)
        self.session = FlightSession.objects.create(
            user_profile=self.profile, active_phase="before-start", is_active=True
        )
        s = self.client.session
        s["flight_session_key"] = self.session.session_key
        s.save()

    def _post_state(self, version):
        return self.client.post(
            reverse("checklist:api_plugin_state"),
            data=json.dumps({"session_id": self.session.pk, "datarefs": {}}),
            content_type="application/json",
            HTTP_AUTHORIZATION=f"Bearer {self.raw_key}",
            HTTP_X_PLUGIN_VERSION=version,
        )

    def _poll(self):
        return self.client.get(
            reverse("checklist:api_poll"), {"procedure": "before-start", "since": 0}
        ).json()

    def test_state_post_records_the_reported_version(self):
        self._post_state("1.0.2")
        self.session.refresh_from_db()
        self.assertEqual(self.session.plugin_version, "1.0.2")

    def test_an_outdated_plugin_produces_a_warning_with_a_download_link(self):
        self._post_state("1.0.2")
        data = self._poll()
        self.assertEqual(data["plugin_status"], "warn")
        self.assertEqual(data["plugin_version"], "1.0.2")
        self.assertTrue(data["plugin_update_url"])

    def test_a_current_plugin_produces_nothing_to_show(self):
        self._post_state("1.1.0")
        data = self._poll()
        self.assertEqual(data["plugin_status"], "ok")
        self.assertEqual(data["plugin_update_url"], "")

    def test_no_banner_once_the_sim_has_disconnected(self):
        """
        A version recorded hours ago would otherwise produce a banner about a
        plugin that is not running — advice the pilot can do nothing with.
        """
        self._post_state("1.0.2")
        FlightSession.objects.filter(pk=self.session.pk).update(
            last_plugin_contact=timezone.now() - timezone.timedelta(minutes=30)
        )
        data = self._poll()
        self.assertFalse(data["sim_connected"])
        self.assertEqual(data["plugin_status"], "ok")
        self.assertEqual(data["plugin_version"], "")


class TestPluginDownloadUrl(TestCase):
    """
    Where an outdated plugin sends the pilot. The failure mode is silent — a
    404 nobody notices until someone tries to update — so the shape is pinned.
    """

    def test_it_does_not_use_the_latest_release_shortcut(self):
        """
        GitHub's /releases/latest is the newest release across ALL tags, and
        app releases (v*) share this repository with plugin releases
        (plugin-v*). A plugin release is normally followed by an app release,
        which makes "latest" an app release carrying no xflow-plugin.zip.

        Observed: with v2.8.0 as the latest release, the old URL redirected to
        /releases/download/v2.8.0/xflow-plugin.zip and returned 404.
        """
        from django.conf import settings

        self.assertNotIn("/releases/latest/", settings.PLUGIN_DOWNLOAD_URL)

    def test_it_points_at_plugin_releases(self):
        from django.conf import settings

        self.assertIn("/releases", settings.PLUGIN_DOWNLOAD_URL)
        self.assertIn("plugin", settings.PLUGIN_DOWNLOAD_URL)

    def test_the_rendered_link_survives_template_escaping(self):
        """
        The URL carries a query string, so autoescaping turns & into &amp; in
        the href. That is correct HTML and browsers resolve it back — this
        pins that the round trip is lossless.
        """
        import html

        from django.conf import settings
        from django.template import Context, Template

        rendered = Template(
            "{% load environment_tags %}"
            "<a href=\"{{ 'PLUGIN_DOWNLOAD_URL'|setting }}\">x</a>"
        ).render(Context({}))
        href = rendered.split('"')[1]
        self.assertEqual(html.unescape(href), settings.PLUGIN_DOWNLOAD_URL)
